version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: 'always'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
#  nginx:
#    image: 'nginx:latest'
#    restart: 'always'
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx config file
#      - ./certs/nginx.crt:/etc/ssl/certs/nginx.crt  # Local SSL certificate mapped to container
#      - ./private/nginx.key:/etc/ssl/private/nginx.key  # Local SSL key mapped to container

