export interface MockClient {
    firstName: string;
    lastName: string;
    age: string;
    cost: number;
    phoneNumber: string;
    idStatus: string;
    expDate: string; // Format: "YYYY-MM-DD"
    doctorCheckStatus: boolean;
    notes: string;
}


export const initialClients: MockClient[] = [
    {
        firstName: "თეა",
        lastName: "კობიაშვილი",
        age: "29",
        cost: 500,
        phoneNumber: "+995-123456789",
        idStatus: "Valid",
        expDate: "2025-01-10",
        doctorCheckStatus: true,
        notes: "No issues",
    },
    {
        firstName: "ლაშა",
        lastName: "ბერიძე",
        age: "35",
        cost: 300,
        phoneNumber: "+995-987654321",
        idStatus: "Expired",
        expDate: "2024-09-20",
        doctorCheckStatus: false,
        notes: "Overdue payment",
    },
    {
        firstName: "ნანა",
        lastName: "გრიგალაშვილი",
        age: "40",
        cost: 450,
        phoneNumber: "+995-654321987",
        idStatus: "Valid",
        expDate: "2024-11-05",
        doctorCheckStatus: true,
        notes: "Requires extra sessions",
    },
    {
        firstName: "ირაკლი",
        lastName: "მაჭავარიანი",
        age: "32",
        cost: 700,
        phoneNumber: "+995-789123654",
        idStatus: "Valid",
        expDate: "2024-08-30",
        doctorCheckStatus: true,
        notes: "Outstanding performance",
    },
    {
        firstName: "ლევან",
        lastName: "ქობულაძე",
        age: "28",
        cost: 200,
        phoneNumber: "+995-321654987",
        idStatus: "Expired",
        expDate: "2024-12-01",
        doctorCheckStatus: false,
        notes: "Needs to reschedule",
    },
    {
        firstName: "ეკატერინე",
        lastName: "მანგლაძე",
        age: "45",
        cost: 1000,
        phoneNumber: "+995-963258741",
        idStatus: "Valid",
        expDate: "2025-02-14",
        doctorCheckStatus: true,
        notes: "Long-term client",
    },
    {
        firstName: "ნიკოლოზ",
        lastName: "ზალდასტანიშვილი",
        age: "37",
        cost: 400,
        phoneNumber: "+995-852963741",
        idStatus: "Valid",
        expDate: "2024-10-30",
        doctorCheckStatus: false,
        notes: "Rescheduled next session",
    },
    {
        firstName: "მაია",
        lastName: "ჩიქოვანი",
        age: "30",
        cost: 350,
        phoneNumber: "+995-741852963",
        idStatus: "Valid",
        expDate: "2025-03-12",
        doctorCheckStatus: true,
        notes: "New client",
    },
    {
        firstName: "გიორგი",
        lastName: "ჩხეიძე",
        age: "33",
        cost: 600,
        phoneNumber: "+995-951753852",
        idStatus: "Expired",
        expDate: "2024-12-25",
        doctorCheckStatus: false,
        notes: "Pending renewal",
    },
    {
        firstName: "ნინო",
        lastName: "სარალიძე",
        age: "39",
        cost: 500,
        phoneNumber: "+995-123654789",
        idStatus: "Valid",
        expDate: "2024-11-22",
        doctorCheckStatus: true,
        notes: "Requested feedback",
    },
    {
        firstName: "ვახტანგ",
        lastName: "ალავიძე",
        age: "29",
        cost: 150,
        phoneNumber: "+995-963741852",
        idStatus: "Expired",
        expDate: "2024-09-30",
        doctorCheckStatus: false,
        notes: "Vacation leave",
    },
    {
        firstName: "ხათუნა",
        lastName: "მაჩაიძე",
        age: "42",
        cost: 700,
        phoneNumber: "+995-321789654",
        idStatus: "Valid",
        expDate: "2024-12-18",
        doctorCheckStatus: true,
        notes: "Will renew soon",
    },
    {
        firstName: "დავით",
        lastName: "ხაბეიშვილი",
        age: "34",
        cost: 250,
        phoneNumber: "+995-951753258",
        idStatus: "Expired",
        expDate: "2024-10-12",
        doctorCheckStatus: true,
        notes: "Missed last session",
    },
    {
        firstName: "თამარ",
        lastName: "ბასილაძე",
        age: "38",
        cost: 450,
        phoneNumber: "+995-852147963",
        idStatus: "Valid",
        expDate: "2024-11-15",
        doctorCheckStatus: true,
        notes: "Recommended for advanced sessions",
    },
    {
        firstName: "ალექსანდრე",
        lastName: "წერეთელი",
        age: "41",
        cost: 650,
        phoneNumber: "+995-789654123",
        idStatus: "Expired",
        expDate: "2024-08-15",
        doctorCheckStatus: false,
        notes: "Requested refund",
    }
];
