name: CI/CD Workflow Laguna

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build Spring Boot application with Gradle
        run: ./gradlew build

      - name: Run Spring Boot tests
        run: ./gradlew test

      - name: Build React application with Webpack
        working-directory: ./laguna-pools-frontend
        run: |
          npm install
          npm run build-webpack

      - name: Run React tests
        working-directory: ./laguna-pools-frontend
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.AWS_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload build artifacts via SCP
        run: |
          scp -i ~/.ssh/id_rsa -r build/libs/laguna-pools-0.0.1.jar ubuntu@"${{ secrets.AWS_HOST }}":/opt/pools/docker/spring-backend/
          scp -i ~/.ssh/id_rsa -r laguna-pools-frontend/dist/* ubuntu@"${{ secrets.AWS_HOST }}":/opt/pools/docker/react-frontend/
          scp -i ~/.ssh/id_rsa docker/docker-compose.yml ubuntu@"${{ secrets.AWS_HOST }}":/opt/pools/docker/
          scp -i ~/.ssh/id_rsa docker/react-frontend/Dockerfile ubuntu@"${{ secrets.AWS_HOST }}":/opt/pools/docker/react-frontend/Dockerfile
          scp -i ~/.ssh/id_rsa docker/spring-backend/Dockerfile ubuntu@"${{ secrets.AWS_HOST }}":/opt/pools/docker/spring-backend/Dockerfile

      - name: Restart Docker services
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@54.224.11.73 "cd /opt/pools/docker && docker compose down && docker compose up -d"
